server:
  port: 8080

spring:
  datasource:
    username: root
    password: Password1234
    url: jdbc:mysql://localhost:3306/search_engine?charset=utf8mb4&useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
# example values

user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/535.21 (KHTML, like Gecko) Chrome/19.0.1042.0 Safari/535.21

indexing-settings:
  sites:
#    - url: https://lenta.ru
#      name: Лента.ру
#    - url: https://skillbox.ru
#      name: Skillbox
    - url: https://kixxlube.ru/
      name: kixx
    - url: https://dombulgakova.ru
      name: Dom Bulgakova
    - url: https://lukoil.ru/
      name: Lukoil

